server:
  port: 8085

mybatis:
  typeAliasesPackage: com.sisp.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cathe-enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: Venti616
    driver-class-name: com.mysql.cj.jdbc.Driver